import Link from "next/link";
import { notFound } from "next/navigation";
import { addCandidateNote, toggleShortlist, updateCandidateReview } from "@/lib/hr/actions";
import { requireHrContext } from "@/lib/hr/context";

export default async function CandidateDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase, workspace } = await requireHrContext();
  const [{ data: candidate }, { data: match }] = await Promise.all([
    supabase.from("candidates").select("*, jobs(id, search_name, minimum_match_score)").eq("id", id).eq("workspace_id", workspace.id).maybeSingle(),
    supabase.from("candidate_matches").select("*").eq("candidate_id", id).eq("workspace_id", workspace.id).order("created_at", { ascending: false }).limit(1).maybeSingle(),
  ]);
  if (!candidate) notFound();
  const { data: notes } = await supabase.from("candidate_notes").select("id, author_id, note, created_at").eq("candidate_id", id).eq("workspace_id", workspace.id).order("created_at", { ascending: false });
  const authorIds = [...new Set((notes ?? []).map((note) => note.author_id))];
  const { data: authors } = authorIds.length ? await supabase.from("profiles").select("id, full_name, email").in("id", authorIds) : { data: [] };
  const authorNames = new Map((authors ?? []).map((author) => [author.id, author.full_name || author.email || "HR user"]));
  const job = Array.isArray(candidate.jobs) ? candidate.jobs[0] : candidate.jobs;
  const shortlistAction = match ? toggleShortlist.bind(null, id, match.id, !match.shortlisted) : undefined;
  const reviewAction = match ? updateCandidateReview.bind(null, id, match.id) : undefined;
  const noteAction = addCandidateNote.bind(null, id, candidate.job_id);
  return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><Link href={job ? `/requisitions/${job.id}/candidates` : "/candidate-pool"} className="text-sm font-semibold text-cyan-700">← {job?.search_name || "Candidate pool"}</Link><h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{candidate.full_name}</h1><p className="mt-2 text-sm text-slate-500">{candidate.current_title} · {candidate.current_company} · {candidate.location}</p></div><div className="flex gap-2">{candidate.profile_url && <a href={candidate.profile_url} target="_blank" rel="noreferrer" className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-800">Open approved profile</a>}{shortlistAction && <form action={shortlistAction}><button className={`rounded-lg px-4 py-2.5 text-sm font-semibold ${match.shortlisted ? "border border-slate-300 bg-white text-slate-800" : "bg-slate-950 text-white"}`}>{match.shortlisted ? "Remove from shortlist" : "Shortlist candidate"}</button></form>}</div></div>
  <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold text-slate-950">Match assessment</h2><p className="mt-1 text-xs text-slate-500">Recommendation only · human review required</p></div><span className={`text-3xl font-semibold ${match && match.overall_score >= Number(job?.minimum_match_score ?? 70) ? "text-emerald-600" : "text-amber-600"}`}>{match ? `${match.overall_score}%` : "—"}</span></div>{match ? <><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-5">{[["Skills",match.skills_score],["Experience",match.experience_score],["Location",match.location_score],["Seniority",match.seniority_score],["Preferred",match.preferred_score]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-slate-50 p-3 text-center"><p className="text-lg font-semibold text-slate-900">{String(value)}%</p><p className="text-xs text-slate-400">{label}</p></div>)}</div><p className="mt-5 text-sm leading-6 text-slate-600">{match.explanation}</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><h3 className="text-sm font-semibold text-emerald-700">Matched strengths</h3><ul className="mt-2 space-y-1 text-sm text-slate-600">{match.strengths?.map((item:string)=><li key={item}>• {item}</li>)}</ul></div><div><h3 className="text-sm font-semibold text-amber-700">Missing requirements</h3><ul className="mt-2 space-y-1 text-sm text-slate-600">{match.missing_requirements?.map((item:string)=><li key={item}>• {item}</li>)}</ul>{match.missing_requirements?.length === 0 && <p className="mt-2 text-sm text-slate-500">No required skill gaps identified.</p>}</div></div></> : <p className="mt-5 text-sm text-slate-500">No score is available because approved job requirements have not been saved.</p>}</section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-950">Candidate profile</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2">{[["Source",candidate.source],["Experience",candidate.years_experience != null ? `${candidate.years_experience} years` : "Not specified"],["Seniority",candidate.seniority || "Not specified"],["Availability",candidate.availability || "Not specified"]].map(([label,value])=><div key={String(label)}><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 text-sm text-slate-700">{value}</dd></div>)}</dl><div className="mt-5 flex flex-wrap gap-2">{candidate.skills?.map((skill:string)=><span key={skill} className="rounded-lg bg-cyan-50 px-2.5 py-1 text-xs font-medium text-cyan-800">{skill}</span>)}</div></section></div>
  <div className="space-y-6">{reviewAction && <form action={reviewAction} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-950">HR review</h2><label className="mt-4 block text-sm font-medium text-slate-700">Candidate status<select name="status" defaultValue={match.review_status} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5">{["New","Under Review","Shortlisted","Contacted","Interview","Rejected","Archived"].map((status)=><option key={status}>{status}</option>)}</select></label><label className="mt-4 block text-sm font-medium text-slate-700">Follow-up date<input name="followUp" type="datetime-local" defaultValue={match.follow_up_at?.slice(0,16) ?? ""} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5"/></label><p className="mt-3 text-xs leading-5 text-slate-500">Changing a status records an activity event. Contact remains a deliberate HR action.</p><button className="mt-4 w-full rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Save review</button></form>}<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-950">Internal notes</h2><form action={noteAction} className="mt-4"><textarea name="note" required rows={4} maxLength={5000} placeholder="Add a private HR note…" className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"/><button className="mt-2 w-full rounded-lg bg-cyan-700 px-4 py-2.5 text-sm font-semibold text-white">Add note</button></form><div className="mt-5 space-y-4">{(notes ?? []).map((note)=><div key={note.id} className="border-t border-slate-100 pt-4"><p className="text-sm leading-6 text-slate-700">{note.note}</p><p className="mt-1 text-xs text-slate-400">{authorNames.get(note.author_id) || "HR user"} · {new Date(note.created_at).toLocaleString()}</p></div>)}{notes?.length === 0 && <p className="text-sm text-slate-500">No internal notes yet.</p>}</div></section></div></div></div>;
}
