import Link from "next/link";
import { notFound } from "next/navigation";
import { addCandidate, startSourcingRun } from "@/lib/hr/actions";
import { requireHrContext } from "@/lib/hr/context";

export default async function RequisitionCandidatesPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string }> }) {
  const { id } = await params;
  const query = await searchParams;
  const { supabase, workspace } = await requireHrContext();
  const [{ data: job }, { data: matches }, { data: run }] = await Promise.all([
    supabase.from("jobs").select("id, search_name, minimum_match_score").eq("id", id).eq("workspace_id", workspace.id).maybeSingle(),
    supabase.from("candidate_matches").select("id, overall_score, review_status, shortlisted, candidates!inner(id, full_name, current_title, current_company, location, profile_url, source, skills)").eq("job_id", id).eq("workspace_id", workspace.id).order("overall_score", { ascending: false }),
    supabase.from("sourcing_runs").select("id, status, error_message, created_at").eq("job_id", id).eq("workspace_id", workspace.id).order("created_at", { ascending: false }).limit(1).maybeSingle(),
  ]);
  if (!job) notFound();
  const start = startSourcingRun.bind(null, id);
  return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Link href={`/requisitions/${id}`} className="text-sm font-semibold text-cyan-700">← {job.search_name}</Link><h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">Matched applicants</h1><p className="mt-2 text-sm text-slate-500">Ranked recommendations from approved candidate sources. HR review is mandatory.</p></div><form action={start}><button className="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">Start approved-source search</button></form></div>
  {run && <div className={`rounded-xl border px-4 py-3 text-sm ${run.status === "configuration_required" || run.status === "failed" ? "border-amber-200 bg-amber-50 text-amber-800" : "border-cyan-200 bg-cyan-50 text-cyan-800"}`}>Latest n8n run: <strong className="capitalize">{run.status.replaceAll("_", " ")}</strong>{run.status === "configuration_required" && " — add N8N_WEBHOOK_URL to enable the connected workflow."}{run.error_message && ` — ${run.error_message}`}</div>}
  {query.error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">The candidate could not be saved. Check the required fields and try again.</div>}
  <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="space-y-3">{(matches ?? []).map((match) => { const candidate = Array.isArray(match.candidates) ? match.candidates[0] : match.candidates; return candidate ? <Link key={match.id} href={`/candidates/${candidate.id}`} className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-cyan-300 sm:flex-row sm:items-center"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-slate-950 text-sm font-semibold text-white">{candidate.full_name.split(" ").map((part:string)=>part[0]).slice(0,2).join("")}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-slate-950">{candidate.full_name}</h2><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">{match.review_status}</span></div><p className="mt-1 text-sm text-slate-500">{candidate.current_title} · {candidate.current_company}</p><p className="mt-2 truncate text-xs text-slate-400">{candidate.skills?.join(" · ") || candidate.source}</p></div><div className={`text-2xl font-semibold ${match.overall_score >= job.minimum_match_score ? "text-emerald-600" : "text-amber-600"}`}>{match.overall_score}%</div></Link> : null; })}{matches?.length === 0 && <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><h2 className="font-semibold text-slate-900">No matched applicants yet</h2><p className="mt-2 text-sm text-slate-500">Start the approved n8n workflow or add a candidate supplied by an authorized source.</p></div>}</section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-950">Add approved candidate</h2><p className="mt-1 text-xs text-slate-500">Manual entry for internal records, referrals, ATS exports, or approved platform results.</p><form action={addCandidate} className="mt-5 space-y-4"><input type="hidden" name="jobId" value={id}/>{[["fullName","Full name *"],["currentTitle","Current title"],["currentCompany","Current company"],["location","Location"],["profileUrl","LinkedIn or approved profile URL"],["source","Candidate source *"],["yearsExperience","Years of experience"],["seniority","Seniority"],["availability","Availability"]].map(([name,label]) => <label key={name} className="block text-sm font-medium text-slate-700">{label}<input name={name} type={name === "yearsExperience" ? "number" : name === "profileUrl" ? "url" : "text"} step={name === "yearsExperience" ? "0.5" : undefined} required={name === "fullName" || name === "source"} defaultValue={name === "source" ? "Manual HR entry" : undefined} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-cyan-600 focus:outline-none focus:ring-2 focus:ring-cyan-100"/></label>)}<label className="block text-sm font-medium text-slate-700">Skills<textarea name="skills" rows={3} placeholder="React, TypeScript, recruiting operations" className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-cyan-600 focus:outline-none focus:ring-2 focus:ring-cyan-100"/></label><button className="w-full rounded-lg bg-cyan-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-cyan-600">Save and calculate match</button></form></section></div></div>;
}
