import Link from "next/link";
import { requireHrContext } from "@/lib/hr/context";

export default async function RequisitionsPage() {
  const { supabase, workspace } = await requireHrContext();
  const { data: jobs } = await supabase.from("jobs").select("id, search_name, company_name, department, location, employment_type, status, minimum_match_score, created_at, archived_at").eq("workspace_id", workspace.id).order("created_at", { ascending: false });
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-semibold tracking-tight text-slate-950">Job requisitions</h1><p className="mt-2 text-sm text-slate-500">Manage hiring requests, approved requirements, and sourcing progress.</p></div><Link href="/requisitions/new" className="rounded-lg bg-slate-950 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-slate-800">New requisition</Link></div>
  <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Position</th><th className="px-5 py-3">Department</th><th className="px-5 py-3">Location</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Threshold</th></tr></thead><tbody className="divide-y divide-slate-100">{(jobs ?? []).map((job) => <tr key={job.id} className={job.archived_at ? "bg-slate-50 opacity-65" : "hover:bg-slate-50"}><td className="px-5 py-4"><Link href={`/requisitions/${job.id}`} className="font-medium text-slate-900 hover:text-cyan-700">{job.search_name}</Link><p className="text-xs text-slate-400">{job.company_name || "Internal requisition"}</p></td><td className="px-5 py-4 text-sm text-slate-600">{job.department || "—"}</td><td className="px-5 py-4 text-sm text-slate-600">{job.location || "—"}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium capitalize text-slate-600">{job.status}</span></td><td className="px-5 py-4 text-sm font-medium text-slate-700">{job.minimum_match_score}%</td></tr>)}{jobs?.length === 0 && <tr><td colSpan={5} className="px-5 py-12 text-center text-sm text-slate-500">No requisitions have been created.</td></tr>}</tbody></table></div></div></div>;
}
