import Link from "next/link";
import { requireHrContext } from "@/lib/hr/context";

export default async function CandidatePoolPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q = "" } = await searchParams;
  const { supabase, workspace } = await requireHrContext();
  let query = supabase.from("candidates").select("id, full_name, current_title, current_company, location, source, skills, status, created_at, jobs(id, search_name)").eq("workspace_id", workspace.id).order("updated_at", { ascending: false });
  if (q.trim()) query = query.or(`full_name.ilike.%${q.trim()}%,current_title.ilike.%${q.trim()}%,current_company.ilike.%${q.trim()}%`);
  const { data: candidates } = await query;
  return <div className="space-y-6"><div><h1 className="text-3xl font-semibold tracking-tight text-slate-950">Candidate pool</h1><p className="mt-2 text-sm text-slate-500">Private candidate records collected only from authorized sources.</p></div><form className="flex max-w-xl gap-2"><input name="q" defaultValue={q} placeholder="Search name, title, or company" className="flex-1 rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-sm focus:border-cyan-600 focus:outline-none focus:ring-2 focus:ring-cyan-100"/><button className="rounded-lg bg-slate-950 px-4 text-sm font-semibold text-white">Search</button></form><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{(candidates ?? []).map((candidate) => <Link key={candidate.id} href={`/candidates/${candidate.id}`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-cyan-300"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-slate-950">{candidate.full_name}</h2><p className="mt-1 text-sm text-slate-500">{candidate.current_title} · {candidate.current_company}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600">{candidate.status}</span></div><p className="mt-4 text-xs text-slate-400">{candidate.location} · {candidate.source}</p><div className="mt-3 flex flex-wrap gap-1.5">{candidate.skills?.slice(0,5).map((skill:string)=><span key={skill} className="rounded-md bg-cyan-50 px-2 py-1 text-xs text-cyan-800">{skill}</span>)}</div></Link>)}{candidates?.length === 0 && <div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center text-sm text-slate-500">No candidates found.</div>}</div></div>;
}
